import type { MetadataRoute } from 'next'

/**
 * Web App Manifest — served at `/manifest.webmanifest`.
 *
 * Required for Chrome/Edge to surface the "Install" prompt and for the
 * installed app to launch in its own window (display: standalone) instead
 * of a browser tab.
 *
 * Icons are generated by `scripts/generate-pwa-icons.mjs` from a single
 * SVG source; edit that script if the brand mark changes.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'CaixaDoBairro — PDV do bairro',
    short_name: 'CaixaDoBairro',
    description:
      'Plataforma moderna de gestão de vendas, clientes e performance do seu negócio.',
    lang: 'pt-BR',
    start_url: '/vendas/nova',
    scope: '/',
    display: 'standalone',
    orientation: 'any',
    background_color: '#0f172a',
    theme_color: '#0f172a',
    categories: ['business', 'productivity', 'finance'],
    icons: [
      {
        src: '/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  }
}
