/**
 * Mapeia texto de bases de código de barras (Cosmos, OFF…) para
 * categorias padrão do mercearia: Alimentos, Bebidas, Limpeza, Higiene.
 */

export const DEFAULT_STORE_CATEGORIES = [
  'Alimentos',
  'Bebidas',
  'Limpeza',
  'Higiene',
] as const

export type DefaultCategoryName = (typeof DEFAULT_STORE_CATEGORIES)[number]

/** Palavras-chave (sem acento) → categoria. Ordem: mais específico primeiro. */
const RULES: { category: DefaultCategoryName; words: string[] }[] = [
  {
    category: 'Bebidas',
    words: [
      'bebida',
      'bebidas',
      'refrigerante',
      'refri',
      'suco',
      'água',
      'agua',
      'cerveja',
      'chopp',
      'vinho',
      'vodka',
      'whisky',
      'whiskey',
      'energético',
      'energetico',
      'isotônico',
      'isotonico',
      'chá',
      'cha pronto',
      'mate',
      'achocolatado',
      'leite integral',
      'leite desnatado',
      'leite semidesnatado',
      'leite uht',
      'iogurte líquido',
      'iogurte liquido',
      'smoothie',
      'nectar',
      'néctar',
      'guarana',
      'guaraná',
      'coca',
      'pepsi',
      'fanta',
      'sprite',
      'h2oh',
      'crystal',
      'bonafont',
    ],
  },
  {
    category: 'Limpeza',
    words: [
      'limpeza',
      'detergente',
      'sabão em pó',
      'sabao em po',
      'sabão líquido',
      'sabao liquido',
      'amaciante',
      'desinfetante',
      'água sanitária',
      'agua sanitaria',
      'alvejante',
      'multiuso',
      'limpador',
      'desengordurante',
      'esponja',
      'bombril',
      'saco de lixo',
      'papel toalha',
      'álcool 70',
      'alcool 70',
      'veja',
      'ypê',
      'ype',
      'omo',
      'ariel',
      'confort',
      'ajax',
      'cif',
    ],
  },
  {
    category: 'Higiene',
    words: [
      'higiene',
      'higiene pessoal',
      'sabonete',
      'shampoo',
      'xampu',
      'condicionador',
      'desodorante',
      'antitranspirante',
      'motionsense',
      'rexona',
      'dove',
      'nivea',
      'colgate',
      'creme dental',
      'pasta de dente',
      'escova dental',
      'fio dental',
      'absorvente',
      'fralda',
      'papel higiênico',
      'papel higienico',
      'lenço umedecido',
      'lenco umedecido',
      'protetor solar',
      'ápice',
      'perfume',
      'colonia',
      'colônia',
      'barba',
      'gilette',
      'gillette',
      'cotonete',
      'algodão',
      'algodao',
      'preservativo',
      'carefree',
      'always',
      'neuttrogena',
      'neutrogena',
      'johnson',
      'monange',
      'seda ',
      'pantene',
      'clear men',
      'heads shoulders',
      'head & shoulders',
    ],
  },
  {
    category: 'Alimentos',
    words: [
      'alimento',
      'alimentos',
      'comida',
      'biscoito',
      'bolacha',
      'chocolate',
      'doce',
      'salgadinho',
      'snack',
      'arroz',
      'feijão',
      'feijao',
      'macarrão',
      'macarrao',
      'massas',
      'açúcar',
      'acucar',
      'café',
      'cafe',
      'óleo',
      'oleo',
      'azeite',
      'farin',
      'trigo',
      'fubá',
      'fuba',
      'leite condensado',
      'creme de leite',
      'manteiga',
      'margarina',
      'queijo',
      'presunto',
      'salsicha',
      'mortadela',
      'carne',
      'frango',
      'peixe',
      'ovo',
      'ovos',
      'milho',
      'ervilha',
      'atum',
      'sardinha',
      'molho',
      'ketchup',
      'maionese',
      'mostarda',
      'temper',
      'sal grosso',
      'pimenta',
      'cereal',
      'granola',
      'aveia',
      'pão',
      'pao',
      'tosta',
      'bolo',
      'sorvete',
      'picolé',
      'picole',
      'bala',
      'chiclete',
      'pirulito',
      'gelatina',
      'pudim',
      'iogurte',
      'requeijão',
      'requeijao',
      'nestle',
      'nestlé',
      'bauducco',
      'piraquê',
      'piraque',
      'elma chips',
      'doritos',
      'ruffles',
      'trident',
      'halls',
      'mentos',
      'toddy',
      'nescau',
      'maggi',
      'knorr',
      'heinz',
    ],
  },
]

function fold(s: string): string {
  return s
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
}

/**
 * Infere categoria a partir de nome/descrição/segmento externo.
 * Retorna null se não houver confianca suficiente.
 */
export function inferCategoryName(
  ...parts: Array<string | null | undefined>
): DefaultCategoryName | null {
  const text = fold(parts.filter(Boolean).join(' · '))
  if (!text.trim()) return null

  for (const rule of RULES) {
    for (const word of rule.words) {
      if (text.includes(fold(word))) return rule.category
    }
  }

  return null
}
